name: 'Readme Stats updater'
description: 'Get Github stats and update repo readme'
inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'GitHub access token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'index.js'